name: Release

on:
  push:
    tags:
      - 'release-*'

jobs:
  build:
    name: Build the IPK
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Docker Build
      run: |
        mkdir bin
        cp -rf ./luci-app-wrtbwmon ./bin/
        docker pull openwrtorg/sdk:x86-64-19.07-SNAPSHOT
        docker run --rm --name=test -u root -v "$(pwd)"/bin/:/home/build/openwrt/bin --privileged=true -d openwrtorg/sdk:x86-64-19.07-SNAPSHOT sleep 1d
        docker exec -i test sed -i 's/git\.openwrt\.org\/project\/luci/github\.com\/openwrt\/luci/g' ./feeds.conf.default
        docker exec -i test ./scripts/feeds update luci
        docker exec -i test ./scripts/feeds install luci
        docker exec -i test mv ./bin/luci-app-wrtbwmon ./package/
        docker exec -i test make defconfig
        docker exec -i test make package/luci-app-wrtbwmon/compile V=s -j$(nproc) | tee >./bin/build.log
        docker stop test
    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd bin && tar -cJf ../build.log.tar.xz build.log && cd ..
        mkdir release
        cp -f ./bin/packages/x86_64/base/*wrtbwmon* ./release/
        set -x
        assets=()
        for asset in ./release/*.ipk; do
          assets+=("-a" "$asset")
        done
        tag_name=$(basename ${{github.ref}})
        hub release create -p "${assets[@]}" -m "$tag_name" "$tag_name"

